### ISSUE TITLE
Indexers screenshots

### ISSUE THREAD

**Issue by traetox** [gravwell/training#19]
Indexers/images/coldstore.png
Indexers/images/docker-wells.png
Indexers/images/greece-accel.png
Indexers/images/hardware.png
Indexers/images/hotstore.png
Indexers/images/prebuffer.png
Indexers/images/replication-restore.png
Indexers/images/stats-accel.png
Indexers/images/tags.png
Indexers/images/wells.png

**Comment by dctootall** [comment]
prebuffer.png is a diagram and not a screenshot.    Other screenshot images have been taken and update incoming

**Comment by traetox** [comment]
https://github.com/gravwell/training/pull/25#event-5927833600
