### ISSUE TITLE
Hands On Lab Improvement

### ISSUE THREAD

**Issue by dctootall** [gravwell/training#3]
Section 4.3.1

The first hands on lab walks through the ingest of logs, and then tells you to perform a few queries to filter the logs.

Issues:

1. Filter instructions have generic instructions:  ex `Filter the auth logs to only include logs from the sshd daemon on the host PORTER`
    *  Section provides no detail on how to format the query Or the expected output
2. Lack of data provided on how the data is being ingested into the system
    *  No detail on ingester configuration being applied,  ie: Tags
    *  No detail on type of data being imported or how it's formatted. 

Suggestions:

 1.  As this is the first hands-on  exercise within the training document,  it may make sense to provide the queries that are expected to be run,  or the expected output.   This may help with providing confidence to the audience that they are doing things correctly as they  start implementing theory provided in previous sections into practical application of the knowledge
 2. Provide a snippet of the raw data,  or high level outline of how the data is being entered into the system.  (ie:  Tags applied to the data, general outline of the log data format).   
     *  Provide a quick outline/image of how the log data imported is formatted.   While Authlog/Syslog formatting is a defined and understood standard,  it would be a mistake to assume that the training audience has the knowledge/experience with Linux System administration needed to know how to search the data on their own.     (ex.  Windows SysAdmins,  Security engineers, Network engineers,  Application support, etc )

**Comment by floren** [comment]
The point of the lab is to show the user what they can do with even the simplest queries. Section 4.3 shows how to use grep to filter for sshd logs from the host named "build". The hope is that when they hit the lab, they can figure out how to change "build" to "porter".

I'd like to preserve that idea of figuring it out for themselves, but I think you're right that there should be more information around what they're doing. Here's what I'm thinking:

1. Add example syslog messages in section 4.3, so they can see how `tag=syslog grep build | grep sshd` will look at the message and find first "build", then "sshd".
2. Explicitly call out in 4.3.1 that the reimport ingester is going to put a bunch of syslog entries into the `syslog` tag
3. Change lab instructions from "Filter the auth logs" to "Filter on the syslog tag"
4. Add call-out in the first step of the hands-on lab that says something like "Hint: Look at the example queries from section 4.3"
