### ISSUE TITLE
Update Caching Section

### ISSUE THREAD

**Issue by ashnwade** [gravwell/training#48]
Lab 7.8.1:
ls -lh /opt/gravwell/cache 
did not show the increased size as indicated for me

I could use either:
ls -lh /opt/gravwell/cache/simple_relay.cache/e
or:
ls -lhR /opt/gravwell/cache (more generic)
had to find the correct subdirectory see the expected change.

 Did not return to 4.0M as indicated. Went to 0 after unpause
before:
![image](https://user-images.githubusercontent.com/107071905/174407497-022c7c2b-bda5-4aeb-b497-fb410ed1c8bd.png)

after:
![image](https://user-images.githubusercontent.com/107071905/174407504-e411a5b7-4398-41f9-9f46-f2c7c721fc43.png)

**Comment by djfritz** [comment]
That entire exercise needs to be rewritten as it reflects the old (~March 2020) cache. Please assign to me.
