### ISSUE TITLE
Moment.js Update

### ISSUE THREAD

**Issue by ashnwade** [gravwell/training#55]
For JS Node in Flows:
Moment JavaScript library
Still popular, but this library is considered a legacy project in maintenance mode. Consider updating to use a different example for loading an external library.

https://momentjs.com/docs/#/-project-status/
**We now generally consider Moment to be a legacy project in maintenance mode. It is not _dead_, but it is indeed _done_.**

**Comment by john-floren-gravwell** [comment]
check out the lodash library instead?
