### ISSUE TITLE
How accelerators work with regards to what queries will engage them

### ISSUE THREAD

**Issue by ashnwade** [gravwell/training#58]
How accelerators work with regards to what queries will engage them. Example: regex acceleration requires the exact same regex in the query in order to engage acceleration.

**Comment by ashnwade** [comment]
Also needed in wiki: https://github.com/gravwell/wiki/issues/432

**Comment by kris-watts-gravwell** [comment]
some specific examples for modules and caveats.

For example regex must match exactly, same with things like fields (must match exactly)
