### ISSUE TITLE
Update Screenshots

### ISSUE THREAD

**Issue by dctootall** [gravwell/training#7]
I have noticed that a large number of the screenshots,  and some of the instructions on where to look for items,   Are based on an older version of the GUI.

I would likely be helpful to update the screenshots within the training to reflect the current look/feel of the application.

**Comment by traetox** [comment]
Make sure we are using the default gravwell dark theme with the candystore renderer theme

- [ ] img/* - all images in this folder
- [ ] img/Webserver/images/* - all images in this folder
